name: Main Workflow

on:
  push:
    branches:
      - main
      - feature

jobs:
  main-workflow:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "Running Main Workflow from feature branch Run 10"
