name: Main Workflow from feature branch

on:
  push:
    branches:
      - main
      - feature

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "Running Main Workflow from feature branch Run 8"
